export type Product = { id: string; title: string; category: string; price: number; compareAt?: number; image: string; color: string; colors: string[]; badge?: string; rating: number; reviews: number; description: string };
export const products: Product[] = [
    { id: 'moab-3', title: 'Moab 3', category: 'Hiking', price: 120, image: 'moab', color: 'Walnut', colors: ['#817562', '#42453b', '#afa494'], badge: 'BEST SELLER', rating: 4.8, reviews: 1248, description: 'The mother of all boots. Out-of-the-box comfort, durable leathers, and a supportive footbed meet best-in-class traction. Your next adventure starts here.' },
    { id: 'moab-speed-2', title: 'Moab Speed 2', category: 'Hiking', price: 140, image: 'speed', color: 'Olive', colors: ['#a5ac69', '#222c29', '#d0bca3'], badge: 'NEW COLORS', rating: 4.7, reviews: 386, description: 'Light on your feet. Big on adventure. Sneaker-light hiking comfort, made for the trail ahead.' },
    { id: 'agility-peak-6', title: 'Agility Peak 6', category: 'Trail Running', price: 150, image: 'agility', color: 'Orange / Chalk', colors: ['#d96736', '#d1d3bd', '#3a4247'], badge: 'NEW ARRIVAL', rating: 4.9, reviews: 214, description: 'Find your flow on any terrain. Responsive cushioning and a grippy outsole keep you focused on the run.' },
    { id: 'jungle-moc', title: 'Jungle Moc', category: 'Everyday', price: 100, image: 'jungle', color: 'Taupe', colors: ['#97816c', '#393633', '#b5a68b'], badge: 'ICONIC COMFORT', rating: 4.8, reviews: 2367, description: 'An icon for a reason. Soft suede and a supportive footbed for easy, everyday comfort. Slip on. Get out.' },
    { id: 'vapor-glove-6', title: 'Vapor Glove 6', category: 'Barefoot', price: 100, image: 'barefoot', color: 'Black', colors: ['#333532', '#9d9e88', '#a46c4b'], rating: 4.7, reviews: 527, description: 'Less between you and the ground. Minimalist, zero-drop design for a natural connection with every step.' },
    { id: 'speedarc', title: 'SpeedARC', category: 'Hiking', price: 170, compareAt: 200, image: 'arc', color: 'Chalk', colors: ['#c4c3b7', '#353e3b', '#ba744f'], badge: 'SALE', rating: 4.8, reviews: 163, description: 'The future of fast hiking. Precision-engineered comfort takes you from city streets to untamed trails.' }
];
export const getProduct = (id: string) => products.find(p => p.id === id);
export const money = (n: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(n);
export type OrderItem = { productId: string; name: string; quantity: number; price: number; variant: string; image: string };
export type Order = { orderId: string; email: string; name: string; items: OrderItem[]; subtotal: number; shippingAmount: number; totalAmount: number; status: string; cardNetwork: string; last4: string; shipping: Record<string, string>; createdAt: string; disputeReason: string | null; disputeId: string | null };
