import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/db';
import { orders, subscribers, messages } from '@/db/schema';
import { and, eq, desc } from 'drizzle-orm';
import { getProduct, products, type OrderItem } from '@/lib/shop';
import { testCards } from '@/shared/shop/test-cards';
import { openLocalDispute } from '@/lib/shop-bridge';
import { handleMockPreAlert } from '@/lib/core/mock-alerts';
const fail = (error: string, status = 400) => NextResponse.json({ error }, { status });
export function serialize(o: typeof orders.$inferSelect) { const { sessionId, ...rest } = o; void sessionId; return { ...rest, subtotal: o.subtotal / 100, shippingAmount: o.shippingAmount / 100, totalAmount: o.totalAmount / 100 }; }
export async function GET(req: NextRequest) {
    try {
        const [resource, id] = req.nextUrl.pathname.split('/').slice(3); if (resource === 'products') { if (id) { const p = getProduct(id); return p ? NextResponse.json({ product: p }) : fail('Product not found', 404); } let list = [...products]; const c = req.nextUrl.searchParams.get('collection'), q = req.nextUrl.searchParams.get('q')?.toLowerCase(); if (c && c !== 'all') list = list.filter(p => c === 'sale' ? p.compareAt : p.category.toLowerCase().replaceAll(' ', '-') === c); if (q) list = list.filter(p => (p.title + ' ' + p.category).toLowerCase().includes(q)); return NextResponse.json({ products: list }); }
        if (resource === 'orders') { const session = req.cookies.get('northline-session')?.value; if (!session) return id ? fail('Order not found in this browser.', 404) : NextResponse.json({ orders: [] }); const condition = id ? eq(orders.orderId, id) : eq(orders.email, (req.nextUrl.searchParams.get('email') || '').trim().toLowerCase()); const list = await db.select().from(orders).where(and(eq(orders.sessionId, session), condition)).orderBy(desc(orders.createdAt)); return id ? (list[0] ? NextResponse.json({ order: serialize(list[0]) }) : fail('Order not found in this browser.', 404)) : NextResponse.json({ orders: list.map(serialize) }); } return fail('Not found', 404);
    } catch { return fail('Unable to load data.', 500); }
}
export async function POST(req: NextRequest) {
    try {
        const origin = req.headers.get('origin'); if (origin && new URL(origin).host !== req.headers.get('host') && new URL(origin).host !== req.headers.get('x-forwarded-host')) return fail('Invalid origin', 403); const [resource, id, operation] = req.nextUrl.pathname.split('/').slice(3); let body; try { body = await req.json(); } catch { return fail('Invalid JSON'); } if (!body || typeof body !== 'object') return fail('Invalid request');
        if (resource === 'checkout') { const email = String(body.email || '').trim().toLowerCase(), name = String(body.name || '').trim(); if (email.length > 254 || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email) || !name || name.length > 150) return fail('Enter a valid name and email address.'); const network = String(body.cardNetwork), number = String(body.cardNumber || '').replace(/\D/g, ''); if (!Object.hasOwn(testCards, network) || number !== testCards[network]) return fail('Use the demo test card. Real card numbers are not accepted.'); const month = Number(body.expMonth), year = Number(body.expYear), now = new Date(); if (!Number.isInteger(month) || month < 1 || month > 12 || !Number.isInteger(year) || year < now.getFullYear() || year > now.getFullYear() + 25 || new Date(year, month, 1) <= now) return fail('Enter a valid future expiration date.'); if (!new RegExp(network === 'amex' ? '^\\d{4}$' : '^\\d{3}$').test(String(body.cvc))) return fail('Enter a valid security code.'); const shipping: Record<string, string> = {}; for (const key of ['name', 'address1', 'city', 'region', 'postalCode']) { const value = String(body.shipping?.[key] || '').trim(); if (!value || value.length > 200) return fail('Please complete all shipping details.'); shipping[key] = value; } shipping.country = 'US'; if (!Array.isArray(body.items) || !body.items.length || body.items.length > 50) return fail('Your bag is empty or too large.'); const items: OrderItem[] = []; for (const line of body.items) { const p = getProduct(String(line?.productId)), q = Number(line?.quantity), variant = String(line?.variant || ''); if (!p || !Number.isInteger(q) || q < 1 || q > 10) return fail('Check your bag quantities.'); if (!/^(Men’s|Women’s) US (\d{1,2}(\.5)?) \/ .+/.test(variant) || variant.length > 100) return fail('Choose a valid size for each item.'); items.push({ productId: p.id, name: p.title, price: p.price, quantity: q, variant, image: p.image }); } const subtotal = Math.round(items.reduce((s, i) => s + i.price * i.quantity, 0) * 100), shippingAmount = subtotal >= 7500 ? 0 : 800; const session = req.cookies.get('northline-session')?.value || crypto.randomUUID(); const [order] = await db.insert(orders).values({ orderId: 'NL-' + crypto.randomUUID().slice(0, 8).toUpperCase(), email, name, items, subtotal, shippingAmount, totalAmount: subtotal + shippingAmount, cardNetwork: network, last4: number.slice(-4), shipping, sessionId: session }).returning(); const response = NextResponse.json({ order: serialize(order) }, { status: 201 }); response.cookies.set('northline-session', session, { httpOnly: true, sameSite: 'lax', secure: req.nextUrl.protocol === 'https:', maxAge: 31536000, path: '/' }); return response; }
        if (resource === 'orders' && id) { const session = req.cookies.get('northline-session')?.value; if (!session) return fail('Order not found', 404); const [order] = await db.select().from(orders).where(and(eq(orders.orderId, id), eq(orders.sessionId, session))); if (!order) return fail('Order not found', 404); if (operation === 'dispute') { const reason = String(body.reason || ''); if (!['Item not received', 'Item not as described', 'Duplicate charge', 'Other'].includes(reason)) return fail('Choose a dispute reason.'); const disputeId = await openLocalDispute(order, reason); return NextResponse.json({ order: { ...serialize(order), status: 'Dispute opened', disputeReason: order.disputeReason || reason, disputeId }, disputeId }); } if (operation === 'prealert') { const alert = await handleMockPreAlert({ eventId: `prealert-${id}`, orderId: id, riskReason: 'customer_contacted_bank', amount: order.totalAmount / 100, currency: 'USD', type: 'mock.pre_dispute_alert', source: 'mock-alerts-simulator' }); return NextResponse.json({ success: true, alert }); } }
        if (resource === 'newsletter' || resource === 'contact') { const email = String(body.email || '').trim().toLowerCase(); if (email.length > 254 || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) return fail('Enter a valid email.'); if (resource === 'newsletter') await db.insert(subscribers).values({ email }).onConflictDoNothing(); else { const message = String(body.message || '').trim(); if (message.length < 5 || message.length > 5000) return fail('Message must be between 5 and 5,000 characters.'); await db.insert(messages).values({ id: crypto.randomUUID(), email, message }); } return NextResponse.json({ success: true }); } return fail('Not found', 404);
    } catch (e) { console.error('Shop request failed', e instanceof Error ? e.message : 'Unknown error'); return fail('Unable to process your request. Please try again.', 500); }
}
