import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/db';
import { orders } from '@/db/schema';
import { desc, eq } from 'drizzle-orm';
import { ensureDemo, openLocalDispute } from '@/lib/shop-bridge';
import { listDisputes, getEvidencePackage } from '@/lib/core/models';
import { toDisputeResponse } from '@/lib/core/dispute-api';
import { serialize } from '@/lib/shop-api';
export const dynamic = 'force-dynamic';
export async function GET() { try { await ensureDemo(); const cases = await listDisputes(); const allOrders = await db.select().from(orders).orderBy(desc(orders.createdAt)); const disputes = await Promise.all(cases.map(async d => { const evidence = await getEvidencePackage(d.disputeId); const p = evidence?.package; const o = allOrders.find(o => o.orderId === d.orderId); return { ...toDisputeResponse(d), customer: o?.name ?? 'Connected merchant', email: o?.email ?? '', score: Number(p?.confidenceScore ?? p?.score ?? 0), seeded: o?.sessionId === 'demo-seed-private' }; })); return NextResponse.json({ disputes, orders: allOrders.map(serialize), integrations: { shopify: !!process.env.SHOPIFY_API_KEY && !!process.env.SHOPIFY_API_SECRET, stripe: !!process.env.STRIPE_SECRET_KEY, paypal: !!process.env.PAYPAL_CLIENT_ID && !!process.env.PAYPAL_CLIENT_SECRET, razorpay: !!process.env.RAZORPAY_KEY_ID && !!process.env.RAZORPAY_KEY_SECRET, ollama: !!process.env.OLLAMA_BASE_URL, adminProtected: !!process.env.SHIELDPAY_ADMIN_PASSWORD } }); } catch (e) { console.error(e); return NextResponse.json({ error: 'Unable to load workspace.' }, { status: 500 }); } }
export async function POST(req: NextRequest) { try { await ensureDemo(); const body = await req.json(); const reason = String(body.reason || 'Item not received'); if (!['Item not received', 'Item not as described', 'Duplicate charge', 'Other'].includes(reason)) return NextResponse.json({ error: 'Invalid reason' }, { status: 400 }); let [order] = await db.select().from(orders).where(eq(orders.orderId, String(body.orderId || 'NL-1048'))); if (!order) return NextResponse.json({ error: 'Order not found' }, { status: 404 }); if (!body.orderId) { const { orderId: _, createdAt: __, disputeId: ___, disputeReason: ____, ...data } = order; void _; void __; void ___; void ____;[order] = await db.insert(orders).values({ ...data, orderId: 'NL-' + crypto.randomUUID().slice(0, 8).toUpperCase(), status: 'Confirmed', sessionId: 'merchant-simulation' }).returning(); } const disputeId = await openLocalDispute(order, reason); return NextResponse.json({ success: true, disputeId, orderId: order.orderId, amount: order.totalAmount / 100, currency: "USD", message: "Simulated dispute created and investigation started" }); } catch { return NextResponse.json({ error: 'Unable to simulate dispute.' }, { status: 500 }); } }
