import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
await mkdir('artifacts', { recursive: true });
const base = process.env.TEST_BASE_URL || 'http://localhost:3000';
const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
const context = await browser.newContext({ viewport: { width: 1440, height: 1050 } }); const page = await context.newPage(); const errors = []; page.on('pageerror', e => errors.push(e.message));
await page.goto(base + '/dashboard', { waitUntil: 'networkidle' }); await page.locator('.cases-table tbody tr').first().waitFor(); assert.match(await page.locator('h1').innerText(), /Your revenue/); await page.screenshot({ path: 'artifacts/dashboard.png', fullPage: true });
await page.getByRole('textbox', { name: 'Search disputes', exact: true }).fill('Olivia'); assert.ok(await page.locator('.cases-table tbody tr').count() >= 1); await page.getByRole('textbox', { name: 'Search disputes', exact: true }).fill('');
await page.goto(base + '/shop', { waitUntil: 'networkidle' }); assert.equal(await page.locator('h1').innerText(), 'FIND YOUR\nOUTSIDE.'); await page.screenshot({ path: 'artifacts/shop.png', fullPage: true }); await page.getByRole('button', { name: 'New Arrivals', exact: true }).click(); assert.equal(await page.locator('.featured-section .product-card').count(), 4);
await page.goto(base + '/shop/products/moab-3'); await page.getByRole('button', { name: 'ADD TO BAG', exact: true }).click(); await page.getByRole('alert').filter({ hasText: 'Please select your size.' }).waitFor(); await page.getByRole('button', { name: '9', exact: true }).click(); await page.getByRole('button', { name: 'ADD TO BAG', exact: true }).click();
await page.goto(base + '/shop/cart'); await page.getByRole('heading', { name: 'ORDER SUMMARY' }).waitFor(); await page.getByRole('button', { name: 'Increase Moab 3 quantity' }).click(); assert.equal(await page.locator('.quantity-control>span').innerText(), '2'); await page.getByRole('link', { name: 'CHECKOUT', exact: true }).click();
const email = `browser-${Date.now()}@example.com`;
for (const [label, value] of [['Email address', email], ['Full name', 'Alex Trail'], ['Street address', '123 Alpine Road'], ['City', 'Boulder'], ['State', 'Colorado'], ['ZIP code', '80301']]) await page.getByRole('textbox', { name: label, exact: true }).fill(value);
await page.getByRole('button', { name: 'Use demo card' }).click(); await page.getByRole('button', { name: /PLACE DEMO ORDER/ }).click(); await page.waitForURL('**/shop/orders/**'); await page.getByRole('heading', { name: 'YOUR NEXT ADVENTURE IS CONFIRMED.' }).waitFor(); const orderUrl = page.url(); const orderId = orderUrl.split('/').pop();
const isolated = await browser.newContext(); assert.equal((await isolated.request.get(orderUrl.replace('/shop/', '/api/shop/'))).status(), 404); await isolated.close();
await page.getByRole('button', { name: 'REPORT AN ISSUE' }).click(); await page.getByRole('button', { name: 'OPEN DEMO DISPUTE' }).click(); await page.getByRole('heading', { name: 'DISPUTE CASE OPENED' }).waitFor();
const retry = await context.request.post(base + `/api/shop/orders/${orderId}/dispute`, { data: { reason: 'Item not received' } }); const result = await retry.json(); assert.equal(retry.status(), 200); assert.equal(result.disputeId, `sim-${orderId}`);
let snap; for (let i = 0; i < 50; i++) { const r = await context.request.get(base + '/api/core/disputes/' + result.disputeId); snap = await r.json(); if (snap.dispute?.status !== 'investigating' && snap.evidence?.evidence?.payment && snap.evidence?.evidence?.fulfillment) break; await new Promise(r => setTimeout(r, 600)); }
assert.equal(snap.dispute.orderId, orderId); assert.equal(snap.dispute.amount, 240); assert.equal(snap.evidence.evidence.order.orderId, orderId); assert.equal(snap.evidence.evidence.payment.amount, 240); assert.equal(snap.evidence.evidence.fulfillment.deliveredAt, null); assert.ok(snap.evidence.ledger.length > 0); assert.notEqual(snap.dispute.status, 'submitted', 'Missing delivery proof must not auto-submit');
await page.goto(base + '/dashboard/disputes/' + result.disputeId, { waitUntil: 'networkidle' }); await page.getByText(orderId, { exact: false }).first().waitFor(); await page.screenshot({ path: 'artifacts/case.png', fullPage: true }); assert.ok((await page.locator('main').innerText()).includes(orderId));
await page.goto(base + '/shop/account'); await page.locator('.order-list-item').first().waitFor(); assert.equal(await page.locator('.order-list-item .status-chip').first().innerText(), 'Dispute opened');
await page.goto(base + '/shop'); await page.getByRole('textbox', { name: 'Email for newsletter' }).fill(email); await page.getByRole('button', { name: 'Subscribe to newsletter' }).click(); await page.getByRole('status').filter({ hasText: 'You’re on the list.' }).waitFor();
await page.goto(base + '/shop/contact'); await page.getByRole('textbox', { name: 'Email address', exact: true }).fill(email); await page.getByRole('textbox', { name: 'How can we help?' }).fill('Please help with my demo order.'); await page.getByRole('button', { name: 'SEND MESSAGE' }).click(); await page.getByRole('status').filter({ hasText: 'saved' }).waitFor();
const settings = await context.request.get(base + '/api/core/merchants/demo-merchant/settings'); assert.equal(settings.status(), 200); const original = (await settings.json()).settings; const update = await context.request.patch(base + '/api/core/merchants/demo-merchant/settings', { data: { settings: { autoSubmitThreshold: 90 } } }); assert.equal(update.status(), 200); assert.equal((await (await context.request.get(base + '/api/core/merchants/demo-merchant/settings')).json()).settings.autoSubmitThreshold, 90); await context.request.patch(base + '/api/core/merchants/demo-merchant/settings', { data: { settings: original } });
for (const provider of ['stripe', 'paypal', 'razorpay']) { const r = await context.request.post(base + '/api/core/webhooks/' + provider, { data: {}, headers: { 'x-mock-commerce': 'true' } }); assert.ok([401, 503].includes(r.status()), 'Unsigned webhooks cannot bypass verification'); }
await page.setViewportSize({ width: 390, height: 844 }); await page.goto(base + '/shop', { waitUntil: 'networkidle' }); await page.screenshot({ path: 'artifacts/shop-mobile.png', fullPage: true }); assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'Shop mobile overflow'); await page.getByRole('button', { name: 'Toggle navigation' }).click(); await page.locator('.mobile-nav').getByRole('link', { name: 'Hiking', exact: true }).click(); await page.waitForURL('**/shop/products?collection=hiking'); assert.equal(await page.locator('.catalog-grid .product-card').count(), 3);
await page.goto(base + '/dashboard', { waitUntil: 'networkidle' }); await page.screenshot({ path: 'artifacts/dashboard-mobile.png', fullPage: true }); assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'Dashboard mobile overflow'); await page.getByRole('button', { name: 'Toggle merchant navigation' }).click(); await page.locator('.workspace-sidebar').getByRole('link', { name: 'Integrations', exact: true }).click(); await page.waitForURL('**/dashboard/integrations');
assert.deepEqual(errors, []); console.log('PASS: dashboard, search, tabs, size validation, cart, checkout, order persistence/privacy, idempotent disputes, real order evidence, safe missing-delivery review, account, newsletter, contact, settings, unsigned-webhook rejection, and responsive mobile navigation.'); console.log('Test order:', orderId, 'Case:', result.disputeId); await browser.close();
